apiVersion: apps/v1
kind: Deployment
metadata:
  name: horovod1 # (optional)改变
  namespace: ai
spec:
  selector:
    matchLabels:
      run: testing-label # Service会通过这个label来代理服务pod
  replicas: 1
  template:
    metadata:
      labels:
        run: testing-label
    spec:
      containers:
      - name: horovod1 # 改变
        image: horovod/horovod:0.18.1-tf1.14.0-torch1.2.0-mxnet1.5.0-py3.6 # 改变
        command: [ "/bin/bash", "-ce", "apt update -y;apt install ssh vim sshpass -y; echo root:admin123|chpasswd;tmp='PermitRootLogin yes';sed -i \"/^#PermitRootLogin/c$tmp\" /etc/ssh/sshd_config; tail -f /dev/null" ]
        resources:
          limits:
            nvidia.com/gpu: 1
        volumeMounts:
        - name: mount-name-testing # (optional)改变
          mountPath: /usr/share/horovod # (optional)改变
      volumes:
        - name: mount-name-testing # (optional)改变
          persistentVolumeClaim:
            claimName: pod-pvc-volume-1  # { pod-pvc-volume-1 pod-pvc-volume-2 pod-pvc-volume-3 }

---
apiVersion: v1
kind: Service
metadata:
  name: svc-testing # (optional)改变
  namespace: ai
spec:
  type: NodePort
  selector:
    run: testing-label
  ports:
    - name: webport      
      protocol: TCP
      nodePort: 30080 # (optional)改变 30000-32767
      port: 8080
      targetPort: 80
    - name: sshport
      protocol: TCP
      nodePort: 30022 # (optional)改变 30000-32767
      port: 40022
      targetPort: 22


