apiVersion: v1
kind: Service
metadata:
  name: pod-slave1-svc
  namespace: ai
spec:
  selector:
    run: pod-ml-slave1
  ports:
    - name: ssh
      protocol: TCP
      port: 22
      targetPort: 22
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-slave1 # (optional)改变
  namespace: ai
  labels:
    run: pod-ml-slave1
spec:
  containers:
  - name: pod-slave1-container
    image: horovod/horovod:0.18.1-tf1.14.0-torch1.2.0-mxnet1.5.0-py3.6
    command: ["/bin/sh", "-c"]
    args: ["cd /usr/share/horovod/SSD-Tensorflow/; \
               apt update -y; \
               apt install ssh vim sshpass -y; \
               echo root:admin123|chpasswd; \
               tmp='PermitRootLogin yes'; \
               sed -i \"/^#PermitRootLogin/c$tmp\" /etc/ssh/sshd_config; \
               /etc/init.d/ssh restart; tail -f /dev/null "]
    resources:
      limits:
        nvidia.com/gpu: 1
    volumeMounts:
    - name: mount-name-testing
      mountPath: /usr/share/horovod
  volumes:
    - name: mount-name-testing
      persistentVolumeClaim:
        claimName: pod-pvc-volume-1
